services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  OAT\Bundle\EnvironmentManagementClientBundle\Http\ArgumentValueResolver\FeatureFlagValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 200 }

  OAT\Bundle\EnvironmentManagementClientBundle\Http\ArgumentValueResolver\TenantIdValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 200 }

  OAT\Bundle\EnvironmentManagementClientBundle\Http\ResponseHelper: ~

  ### vendor services
  OAT\Library\EnvironmentManagementClient\Http\FeatureFlagExtractorInterface:
    class: OAT\Library\EnvironmentManagementClient\Http\FeatureFlagHeaderExtractor

  OAT\Library\EnvironmentManagementClient\Http\JWTTokenExtractorInterface:
    class: OAT\Library\EnvironmentManagementClient\Http\BearerJWTTokenExtractor

  OAT\Library\EnvironmentManagementClient\Http\TenantIdExtractorInterface:
    class: OAT\Library\EnvironmentManagementClient\Http\TenantIdExtractor

  OAT\Library\EnvironmentManagementClient\Http\RegistrationIdExtractorInterface:
    class: OAT\Library\EnvironmentManagementClient\Http\RegistrationIdExtractor

  OAT\Library\EnvironmentManagementClient\Http\AuthorizationDetailsMarkerInterface:
    class: OAT\Library\EnvironmentManagementClient\Http\AuthorizationDetailsHeaderMarker

  OAT\Library\EnvironmentManagementClient\Grpc\Factory\GrpcClientFactory:
    arguments:
      - '@Psr\Log\LoggerInterface'

  Oat\Envmgmt\Sidecar\ConfigServiceClient:
    factory: ['@OAT\Library\EnvironmentManagementClient\Grpc\Factory\GrpcClientFactory', 'createConfigServiceClient']

  Oat\Envmgmt\Sidecar\FeatureFlagServiceClient:
    factory: ['@OAT\Library\EnvironmentManagementClient\Grpc\Factory\GrpcClientFactory', 'createFeatureFlagServiceClient']

  Oat\Envmgmt\Sidecar\LtiServiceClient:
    factory: ['@OAT\Library\EnvironmentManagementClient\Grpc\Factory\GrpcClientFactory', 'createLtiServiceClient']

  Oat\Envmgmt\Sidecar\Oauth2ClientServiceClient:
    factory: ['@OAT\Library\EnvironmentManagementClient\Grpc\Factory\GrpcClientFactory', 'createOauth2ClientServiceClient']

  OAT\Library\EnvironmentManagementClient\Repository\ConfigurationRepositoryInterface:
    class: OAT\Library\EnvironmentManagementClient\Grpc\ConfigurationRepository
    arguments:
      - '@Oat\Envmgmt\Sidecar\ConfigServiceClient'
      - '@Psr\Log\LoggerInterface'

  OAT\Library\EnvironmentManagementClient\Repository\FeatureFlagRepositoryInterface:
    class: OAT\Library\EnvironmentManagementClient\Grpc\FeatureFlagRepository
    arguments:
      - '@Oat\Envmgmt\Sidecar\FeatureFlagServiceClient'
      - '@Psr\Log\LoggerInterface'

  OAT\Library\EnvironmentManagementClient\Repository\LtiRegistrationRepositoryInterface:
    class: OAT\Library\EnvironmentManagementClient\Grpc\LtiRegistrationRepository
    arguments:
      - '@Oat\Envmgmt\Sidecar\LtiServiceClient'
      - '@Psr\Log\LoggerInterface'

  OAT\Library\EnvironmentManagementClient\Repository\OAuth2ClientRepositoryInterface:
    class: OAT\Library\EnvironmentManagementClient\Grpc\OAuth2ClientRepository
    arguments:
      - '@Oat\Envmgmt\Sidecar\Oauth2ClientServiceClient'
      - '@Psr\Log\LoggerInterface'

  Nyholm\Psr7\Factory\Psr17Factory: ~

  Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
    class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
    arguments:
      - '@Nyholm\Psr7\Factory\Psr17Factory'
      - '@Nyholm\Psr7\Factory\Psr17Factory'
      - '@Nyholm\Psr7\Factory\Psr17Factory'
      - '@Nyholm\Psr7\Factory\Psr17Factory'

  Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
    class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory
